const list = [
    {
      id: 1,
      title: "Pakistan Tour",
      author: "No Of Days : 10 ",
      price: 20000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Air",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 2,
      title: "Pakistan Tour",
      author: "No Of Days : 11",
      price: 22000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Van",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 3,
      title: "Pakistan Tour",
      author: "No Of Days : 12 ",
      price: 24000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Bus",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 4,
      title: "Pakistan Tour",
      author: "No Of Days : 13 ",
      price: 25000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Van",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 5,
      title: "Pakistan Tour",
      author: "No Of Days : 14 ",
      price: 26000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Bus",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png.jpg",
      amount: 1,
    },
    {
      id: 6,
      title: "Pakistan Tour",
      author: "No Of Days : 15 ",
      price: 28000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Air",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 7,
      title: "Pakistan Tour",
      author: "No Of Days : 16  ",
      price: 30000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Air",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 8,
      title: "Pakistan Tour",
      author: "No Of Days :17",
      price: 31000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Van",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 9,
      title: "Pakistan Tour",
      author: "No Of Days : 18",
      price: 31500,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Air",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 10,
      title: "Pakistan Tour",
      author: "No Of Days : 19",
      price: 32000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Van",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 11,
      title: "Pakistan Tour",
      author: "No Of Days : 20 ",
      price: 33000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Air",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
    {
      id: 12,
      title: "Pakistan Tour",
      author: "No Of Days : 21 ",
      price: 35000,
      Accomodation:"Accomodation : Guest House",
      convenience : "convenience : Van",
      img: "https://lh3.googleusercontent.com/-LpBroolksh0/YVeQcv7rnzI/AAAAAAAAHZU/8cuDCOGcnmg4sq9uG6wxZnxkwRWbhWtzwCLcBGAsYHQ/w320-h400/image.png",
      amount: 1,
    },
  ];
  
  export default list;